image: kradalby/ci-tox
git:
  path: github.com/kradalby/sourceapi

env:

script:
    - pip install tox
    - tox

notify:
  email:
    recipients:
      - kradalby@kradalby.no


deploy:
  bash:
    script:
        - 'pip install ansible'
        - 'git clone https://github.com/kradalby/plays.git'
        - 'ansible-playbook -i plays/inventory plays/deploy/sourceapi.yml'
