build:
    image: kradalby/ci-tox:latest
    pull: true
    commands:
      - tox

notify:
  email:
    from: drone@fap.no
    host: smtp.stud.ntnu.no
    port: 25
    recipients:
      - kradalby@kradalby.no

deploy:
  ssh:
    host: onyx.fap.no
    user: www
    port: 22
    commands:
      - cd /usr/local/www/source.fap.no
      - git pull
      - supervisorctl restart uwsgi_sourceapi
