build:
    image: synapse/tox:latest
    pull: true
    command:
        - tox

notify:
  email:
    from: drone@fap.no
    host: smtp.stud.ntnu.no
    port: 25
    recipients:
      - kradalby@kradalby.no


#deploy:
#  bash:
#    script:
#        - 'git clone https://github.com/kradalby/plays.git'
#        - 'ansible-playbook -i plays/inventory plays/deploy/sourceapi.yml'
