---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: test
  pull: if-not-exists
  image: python:3.5.2
  commands:
  - pip install tox
  - cp config.py.example config.py
  - tox

- name: build
  pull: if-not-exists
  image: banzaicloud/drone-kaniko
  settings:
    repo: kradalby/sourceapi
    tags:
    - ${DRONE_COMMIT_SHA:0:8}
    - latest
    cache: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    branch:
    - master

- name: deploy
  pull: if-not-exists
  image: quay.io/honestbee/drone-kubernetes
  settings:
    container: common
    deployment: sourceapi
    namespace: sourceapi
    repo: kradalby/sourceapi
    tag:
    - ${DRONE_COMMIT_SHA:0:8}
  environment:
    KUBERNETES_CERT:
      from_secret: kubernetes_cert
    KUBERNETES_SERVER:
      from_secret: kubernetes_server
    KUBERNETES_TOKEN:
      from_secret: kubernetes_token
  when:
    branch:
    - master

- name: notify
  pull: if-not-exists
  image: drillster/drone-email
  settings:
    from: drone@drone.fap.no
    host: smtp.fap.no
    port: 25
    recipients:
    - kradalby@kradalby.no
    skip_verify: true
  when:
    status:
    - success
    - changed
    - failure
