build:
    image: kradalby/ci-tox
    command:
        - tox

notify:
  email:
    recipients:
      - kradalby@kradalby.no


#deploy:
#  bash:
#    script:
#        - 'git clone https://github.com/kradalby/plays.git'
#        - 'ansible-playbook -i plays/inventory plays/deploy/sourceapi.yml'
