build:
    image: kradalby/ci-tox:latest
    pull: true
    commands:
      - cp config.py.example config.py
      - tox

notify:
  email:
    from: drone@fap.no
    host: smtp.stud.ntnu.no
    port: 25
    recipients:
      - kradalby@kradalby.no

publish:
  docker:
    registry: registry.fap.no
    repo: sourceapi/sourceapi
    tag: latest
    insecure: true
    when:
        branch: master
    load: docker/image.tar
    save:
      destination: docker/image.tar
      tag: latest

deploy:
  ssh:
    host:
     - primeape.terra.fap.no
    user: root
    port: 22
    sleep: 2
    commands:
      - docker pull registry.fap.no/sourceapi/sourceapi:latest
      - docker-compose -f /srv/docker/sourceapi/docker-compose.yml stop
      - docker-compose -f /srv/docker/sourceapi/docker-compose.yml up -d
    when:
        branch: master
