"""empty message

Revision ID: 172907ed2d58
Revises: None
Create Date: 2016-03-23 11:30:09.757396

"""

# revision identifiers, used by Alembic.
revision = '172907ed2d58'
down_revision = None

# pyre-fixme[21]: Could not find `alembic`.
from alembic import op
# pyre-fixme[21]: Could not find `sqlalchemy`.
import sqlalchemy as sa


def upgrade() -> None:
    ### commands auto generated by Alembic - please adjust! ###
    # pyre-fixme[18]: Global name `alembic` is undefined.
    op.add_column('query', sa.Column('user_agent', sa.String(length=65536), nullable=True))
    ### end Alembic commands ###


def downgrade() -> None:
    ### commands auto generated by Alembic - please adjust! ###
    # pyre-fixme[18]: Global name `alembic` is undefined.
    op.drop_column('query', 'user_agent')
    ### end Alembic commands ###
